---
title: "Grade analysis"
author: "Leslie HUYNH"
format: html
---
https://github.com/leslie3001/r-101-grade-analysis.git 

```{r}
#| message: false
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)
here::i_am("grade_analysis.qmd")
```
## Question 1
```{r}
#| message: false
grades <- vroom(here("grades.csv"))
```
## Question 2
```{r}
grades |> summarise(
  min_exam=min(Exam, na.rm=TRUE),
  max_exam=max(Exam, na.rm=TRUE),
  med_exam=median(Exam, na.rm=TRUE),
  mean_exam=mean(Exam, na.rm=TRUE)
) |>
  knitr::kable()
```

## Question 3
```{r}
missing <- grades |> filter(is.na(Exam)) |> nrow()
```
`r missing` students did not take the final exam. 

## Question 4
```{r}
grades |> filter(Exam!="NA")|>
  ggplot(aes(x=Exam))+ 
  geom_bar()+
  scale_x_continuous(breaks=0:20)+
  xlab("Final exam grades")
```
This graph shows the repartition of grades at the Exam. 

## Question 5
```{r}
grades |> group_by(Group)|> summarise(number_group=n())|>
  knitr::kable()
```

## Question 6
```{r}
grades |> group_by(Group) |> 
  ggplot(aes(y=Group)) + geom_bar()
```
This graph gives the repartition of students in each group.

## Question 7
```{r}
grades |> filter(Exam!="NA") |>
  ggplot(aes(x=Group, y=Exam))+geom_boxplot()+
  ylab("Grades")
```

```{r}
grades |> filter(Exam!="NA") |>
  ggplot(aes(x=Group, y=Exam))+geom_violin()+ coord_flip()+
  ylab("Grades")
```
These two graphs shows the grades of each group. 

## Question 8
```{r}
missing_grades <- grades |> group_by(Group) |> reframe(missexam=is.na(Exam))
missing_grades |> group_by(Group) |> summarise(N=sum(missexam==TRUE)) |>
knitr::kable()
```

## Question 9
```{r}
missing_grades |> group_by(Group) |> summarise(N=sum(missexam==TRUE)) |>
ggplot(aes(y=Group, x=N)) + 
  geom_col() + 
  scale_x_continuous(breaks=0:10)+
  labs(title="Number of students who missed the Exam in each group")

```





